# Generated by Django 5.2.5 on 2025-08-20 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('FILE', 'File'), ('DIR', 'Directory'), ('TAG', 'Tag')], max_length=8)),
                ('path', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=128, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='graphfs_nod_name_6afaf7_idx'), models.Index(fields=['type'], name='graphfs_nod_type_76c814_idx')],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('CONTAINS', 'Contains'), ('SYMLINK', 'Symlink'), ('TAGGED', 'Tagged'), ('DUPLICATE', 'Duplicate')], max_length=16)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='graphfs.node')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='graphfs.node')),
            ],
            options={
                'indexes': [models.Index(fields=['edge_type'], name='graphfs_edg_edge_ty_f936fc_idx')],
                'unique_together': {('src', 'dst', 'edge_type')},
            },
        ),
    ]
